# Generated by Django 2.2.2 on 2019-06-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0003_auto_20190610_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='state',
            new_name='state_id',
        ),
    ]
